### ISSUE TITLE
BLEU 1-4, which one?

### ISSUE THREAD

**Issue by fajri91** [mjpost/sacrebleu#105]
Sorry, I couldn't find how to compute BLEU-1, 2, 3, 4 from this code

```
import sacrebleu
bleu = sacrebleu.corpus_bleu(preds, [golds])
print (bleu.score)
```

is the `bleu.precisions` BLEU (1-4) ?

**Comment by martinpopel** [comment]
What do you mean by "BLEU-1, 2, 3, 4"?
`bleu.precisions` are the unigram, bigram, trigram and 4-gram modified precisions, i.e. without brevity penalty.

**Comment by fajri91** [comment]
BLUE-1. BLEU-2, BLEU-3, and BLEU-4: The n-gram precision mentioned in the original paper https://www.aclweb.org/anthology/P02-1040.pdf, and widely used in some MT and generation papers. 

Ah right, it seems it does. Thanks

**Comment by fajri91** [comment]
I think the current `sacrebleu.corpus_bleu` gives us the bleu-4 score.

As the [code](https://github.com/mjpost/sacrebleu/blob/e22640c996ca48d018fd974ba26a052180f4c77d/sacrebleu/metrics/bleu.py#L89) sets `NGRAM_ORDER` as a constant value. 

I do some tricks, to obtain bleu(1-4), by modifying the static function. 
(Anyone who see this post), Please let me know if it's correct.

```
from collections import Counter
from sacrebleu import BLEU

for idx in range(1,5):
    BLEU.NGRAM_ORDER=idx
    def extract_ngrams(line, min_order=1, max_order=BLEU.NGRAM_ORDER) -> Counter:
        """Extracts all the ngrams (min_order <= n <= max_order) from a sequence of tokens.
        :param line: A segment containing a sequence of words.
        :param min_order: Minimum n-gram length (default: 1).
        :param max_order: Maximum n-gram length (default: NGRAM_ORDER).
        :return: a dictionary containing ngrams and counts
        """
        ngrams = Counter()
        tokens = line.split()
        for n in range(min_order, max_order + 1):
            for i in range(0, len(tokens) - n + 1):
                ngram = ' '.join(tokens[i: i + n])
                ngrams[ngram] += 1
        return ngrams
    BLEU.extract_ngrams = extract_ngrams
    import sacrebleu
    bleu = sacrebleu.corpus_bleu(preds, [golds])
    print ('bleu-' +str(idx), bleu.score)
```

**Comment by martinpopel** [comment]
There is no "BLUE-1. BLEU-2, BLEU-3, and BLEU-4" in the original paper. It defines modified n-gram precision score, but it is denoted *p<sub>n</sub>*.
You are right that "BLUE-1. BLEU-2, BLEU-3, and BLEU-4" were used in several papers, but unfortunately with very different meanings: in addition to modified n-gram precision, e.g. BLEU computed on n references or BLEU with N=n instead of the standard N=4. Thus, I suggest not using the ambiguous terms "BLUE-1. BLEU-2, BLEU-3, and BLEU-4" (or at least always properly define what does it mean).

> I think what I want is the unmodified version,

I don't think so. The "modified" is there because of clipping - see Section 2.1 of the original paper.

> `blue.precisions` somehow gives me lower BLEU(1-4) scores than it should.

And how do you know what the precisions should be?
I am quite sure `blue.precisions` reports the modified n-gram precision scores correctly. Note that you can see these precisions also when you print the BLEU object (with the default `score_only=False`) or when you use `sacrebleu` from the command line: e.g. "32.97 66.1/40.2/26.6/18.1", where 66.1 is the modified unigram precision score etc.

> I do some tricks ... Please let me know if it's correct.

Probably not. Your code computes alternative BLEU with N=idx instead of the standard N=4. So e.g. for idx=3 it is not the (modified) trigram precision, but a geometric mean of unigram, bigram and trigram precisions multiplied by the brevity penalty. Moreover, you compute it in a very inefficient way (you could extract ngrams just once and compute these alternative BLEU scores from the modified precisions and the brevity penalty, which is also reported by default as BP).

**Comment by fajri91** [comment]
> And how do you know what the precisions should be?

I am evaluating text generation task, with BLEU, METEOR, and R-L. 
I am referring to Table 5 in [this paper](https://arxiv.org/pdf/1910.10274.pdf) where their best result is:
`Blue-1: 42.54, Blue-2: 26.14, Blue-3: 17.30, Blue-4: 12.36, Meteor: 19.04, R-L: 44.05`
Whereas, in my experiments:
Exp1: `SacreBlue: 11.32, Meteor: 16.92 , R-L: 41.85`
Exp2: `SacreBlue: 15.95, Meteor: 17.68 , R-L: 41.82`
I am not sure how they obtain the Bleu-(1-4) scores. If the SacreBlue output is Bleu-4, the increasing scores are just not in line between Bleu-4 and Meteor (compared to the paper result).

> Probably not. Your code computes alternative BLEU with N=idx instead of the standard N=4. So e.g. for idx=3 it is not the (modified) trigram precision, but a geometric mean of unigram, bigram and trigram precisions multiplied by the brevity penalty. 

Yeah, you are right.  I talk to my friend, and she said the same thing as you. She defines BLEU-3, for instance as the geometric mean of (1,2,3) gram. 

> Moreover, you compute it in a very inefficient way (you could extract n-grams just once and compute these alternative BLEU scores from the modified precisions and the brevity penalty, which is also reported by default as BP).

It is obviously inefficient. I just change it quickly, to see how is the result as sacreBLUE haven't supported these variants.

**Comment by ozancaglayan** [comment]
This is a very ambiguous issue which became more prominent esp. after the
introduction of pycocoeval tools. That utility exposes Bleu1 to 4 as
different metrics, along with meteor, rouge and cider. I think they are
valid BLEU scores which are computed with N set to 1, 2, 3 and 4.

It is possible that this paper used that tool as well. But ambiguity arises
from the fact that multibleu and sacrebleu reports also the n-gram
precisions but those are not equal to BLEU-n scores. So I presume that many
papers in the wild may mistakenly report one for the other, or vice versa.

you can give pycocotools a try, and also you can then compare those results
to your modified bleu-n through sacrebleu.
