### ISSUE TITLE
Getting error in Running Code. 

### ISSUE THREAD

**Issue by ykkhan** [mjpost/sacrebleu#112]
I am not getting where is the error. Please, guide me to solve this
![Screenshot from 2020-08-07 19-28-46](https://user-images.githubusercontent.com/42977303/89675274-17769c80-d903-11ea-9a9a-8ff4b5e3ff2e.png)

**Comment by ozancaglayan** [comment]
Hi, does that `output.detok.txt` even exist in that folder?

**Comment by ykkhan** [comment]
No, it is not present
I am not getting why it is not created, although, i have run it many time from start to this point.

**Comment by ykkhan** [comment]
Kindly check this code and output. Is it correct or am I making mistake.?
![output](https://user-images.githubusercontent.com/42977303/89705325-dff50800-d975-11ea-9f8a-cdf231f1c311.png)

**Comment by martinpopel** [comment]
@ykkhan It seems you are following the [Quick Start](https://github.com/mjpost/sacrebleu#quick-start) (now with wmt17 instead of wmt14), which says "After tokenizing, translating, and detokenizing it". This means you should translate the English sentences in `wmt17-de-en.src` into German with a machine translation system of your choice and store the resulting German sentences in `output.detok.txt`.

> Kindly check this code and output. Is it correct or am I making mistake.?

You used the English source instead of the translation. This resulted in BLEU=3.3 (out of 100 maximum), which is a very low value, which is expected here -- probably only proper names match the German reference translation.
