### ISSUE TITLE
Use sacreblue in TensorBoard

### ISSUE THREAD

**Issue by MaryaAI** [mjpost/sacrebleu#180]
How can I show sacreblue results on TensorBoard?

**Comment by martinpopel** [comment]
You can use sacrebleu as a library and write a script which will generate the event file suitable for TensorBoard.
I implemented a [similar script](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/bin/t2t_bleu.py) using the T2T implementation of BLEU instead of SacreBLEU, but it should be easy to substitute `bleu_hook.bleu_wrapper` for calling sacrebleu as shown in https://github.com/mjpost/sacrebleu#using-sacrebleu-from-python.
