### ISSUE TITLE
Default params for calculating bleu

### ISSUE THREAD

**Issue by base-y** [mjpost/sacrebleu#195]
Hi, what exactly are the default set of parameters (tokenize, smooth_method, smooth_value) to calculate BLEU? I see default smooth_method is `floor` and `tokenize='none'` (which uses 13a tokenizer) in this repo while huggingface `datasets` has default smooth_method=`exp` and `tokenize=None` (which uses BaseTokenizer)

would like to know the default one used in research.

And also, whats the difference b/w `raw_corpus_bleu` and `corpus_bleu` methods in `compat.py`?

**Comment by martinpopel** [comment]
There are different default values for different use cases (sentence-level BLEU, legacy methods). If you run e.g. `sacrebleu -i output.detok.txt -t wmt17 -l en-de` without any other parameters, you will see also the [SacreBLEU signature](https://github.com/mjpost/sacrebleu#json-output), which is in this case `nrefs:1|case:mixed|eff:no|tok:13a|smooth:exp|version:2.0.0`. So the default tokenization is `13a` and the default smoothing method `exp`.

**Comment by martinpopel** [comment]
See [the source code of BaseTokenizer](https://github.com/mjpost/sacrebleu/blob/master/sacrebleu/tokenizers/tokenizer_base.py#L12-L19) and I hope you'll understand why the respective parameter is called `--tok=none`. This means that no spaces are added to the lines, so tokens are separated at original whitespace only. Note that this is useful in very rare cases only (checking the effect of non-standard tokenizers) and [a warning](https://github.com/mjpost/sacrebleu/blob/990b3e2/sacrebleu/sacrebleu.py#L314-L318) is issued if `--tok=none` is used.
So why is it called `BaseTokenizer` rather than `NoneTokenizer` when it does not even separate commas? It is the base class for other tokenizers.
Python `None` is the usual way for encoding a default value, so I think it should be kept as is and I don't see any risk of ambiguity.

**Comment by mjpost** [comment]
I can see how the use of "none" to mean "don't use any tokenization" can be confusing at the code level. For the v2.2 release, I created a separate tokenizer and added some comments that I hope will help clarify this.
