### ISSUE TITLE
GitHub workflows CI tests fail on Python 3.6

### ISSUE THREAD

**Issue by martinpopel** [mjpost/sacrebleu#233]
I've tried to solve it in #232, with no success. So I give up.
If someone knows how to fix it, please help us. Otherwise, I will drop support for Python 3.6 (both for the tests and `python_requires='>=3.6',` in setup.py, as it does not make sense to support a Python version which is not covered by CI).

**Comment by ales-t** [comment]
Investigating this a bit further, it seems that `ubuntu-latest` is now 22.04 and Python 3.6 is not supported there in GitHub actions: https://github.com/actions/setup-python/issues/544

See also this versions manifest: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

One possibility would be to do the following changes:

* add a new os `ubuntu-20.04` to the list of platforms, in order to keep testing python 3.6
* create a new exclude rule for os `ubuntu-latest` and python 3.6
* while we're at it, add python 3.11

WDYT? I'd be happy to create a PR for that.

**Comment by ales-t** [comment]
I had to update a bunch of dependencies quite carefully and now it seems like CI should work. However, I get (randomly, AFAICT) internal errors for some jobs when the actions run: https://github.com/mjpost/sacrebleu/actions/runs/4938094678

Github reports no outstanding warnings or issues though, so maybe simply re-running the CI pipeline in a few hours could be worth a try? (I don't have permissions to do that it seems.)
