### ISSUE TITLE
Should BLEU score be dependent on the order of the sequences?

### ISSUE THREAD

**Issue by davidgonmar** [mjpost/sacrebleu#272]
Hey! Using sacrebleu to evaluate a model for a project of mine, and just noticed this:
```python
        bleu = sacrebleu.corpus_bleu(decoded_cands, decoded_refs).score

        randper = torch.randperm(len(decoded_refs))
        decoded_refs = [decoded_refs[i] for i in randper]
        decoded_cands = [decoded_cands[i] for i in randper]
        bleu_rand0 = sacrebleu.corpus_bleu(decoded_cands, decoded_refs).score

        randper = range(len(decoded_refs))
        decoded_refs = [decoded_refs[i] for i in randper]
        decoded_cands = [decoded_cands[i] for i in randper]
        bleu_rand1 = sacrebleu.corpus_bleu(decoded_cands, decoded_refs).score

        print("bleu 0: ", bleu, "bleu 1: ", bleu_rand0, "bleu 2: ", bleu_rand1)
```
Here, the order of the sentences make the BLEU score change. `bleu` is identical to `bleu_rand1` but varies drastically with `bleu_rand0` (randomly permuted). I am not an expert in this, but what is the reason it can vary so much (some permutations will result in about a score 20 and others in a score in the 60s). Am I doing something wrong? Thanks in advance!

**Comment by martinpopel** [comment]
If you have a single reference translation for each sentence, you should use `corpus_bleu(decoded_cands, [decoded_refs])` instead of `corpus_bleu(decoded_cands, decoded_refs)`. Otherwise, you are treating each character in `decoded_refs` as a (single-character) sentence, so the BLEU scores are meaningless.
See https://github.com/mjpost/sacrebleu/tree/master#using-sacrebleu-from-python, which shows a 2-reference example:
```python
refs = [ # First set of references
         ['The dog bit the man.', 'It was not unexpected.', 'The man bit him first.'],
         # Second set of references
         ['The dog had bit the man.', 'No one was surprised.', 'The man had bitten the dog.'],
       ]
sys = ['The dog bit the man.', "It wasn't surprising.", 'The man had just bitten him.']

from sacrebleu.metrics import BLEU
bleu = BLEU()
bleu.corpus_score(sys, refs)
```
where the last three lines are [equivalent](https://github.com/mjpost/sacrebleu/blob/5af5a3afd859f5825812feb14084a30b34960ee3/sacrebleu/compat.py#L32-L37) (unless the language is zh, ja or ko) to the legacy way you use:
```python
import sacrebleu
sacrebleu.corpus_bleu(sys, refs)
```

I admit `corpus_bleu(hypotheses, references)` may be misleading because "hypotheses" means a single hypothesis for each sentence in the document, while "references" means "A **sequence of reference documents** with document being defined as a sequence of reference strings" (according to the [documentation](https://github.com/mjpost/sacrebleu/blob/5af5a3afd859f5825812feb14084a30b34960ee3/sacrebleu/compat.py#L22)). This is also reflected in the method parameters signature (`hypotheses: Sequence[str], references: Sequence[Sequence[str]]`).
Unfortunately, both `[["sent 1", "sent 2"]]` and `["sent 1", "sent 2"]` and even a single string `"sent 1"` pass the `Sequence[Sequence[str]]` type check (I am not sure why). Maybe we could add an explicit check for this common misuse.

**Comment by davidgonmar** [comment]
> If you have a single reference translation for each sentence, you should use `corpus_bleu(decoded_cands, [decoded_refs])` instead of `corpus_bleu(decoded_cands, decoded_refs)`. Otherwise, you are treating each character in `decoded_refs` as a (single-character) sentence, so the BLEU scores are meaningless. See https://github.com/mjpost/sacrebleu/tree/master#using-sacrebleu-from-python, which shows a 2-reference example:
> 
> ```python
> refs = [ # First set of references
>          ['The dog bit the man.', 'It was not unexpected.', 'The man bit him first.'],
>          # Second set of references
>          ['The dog had bit the man.', 'No one was surprised.', 'The man had bitten the dog.'],
>        ]
> sys = ['The dog bit the man.', "It wasn't surprising.", 'The man had just bitten him.']
> 
> from sacrebleu.metrics import BLEU
> bleu = BLEU()
> bleu.corpus_score(sys, refs)
> ```
> 
> where the last three lines are [equivalent](https://github.com/mjpost/sacrebleu/blob/5af5a3afd859f5825812feb14084a30b34960ee3/sacrebleu/compat.py#L32-L37) (unless the language is zh, ja or ko) to the legacy way you use:
> 
> ```python
> import sacrebleu
> sacrebleu.corpus_bleu(sys, refs)
> ```
> 
> I admit `corpus_bleu(hypotheses, references)` may be misleading because "hypotheses" means a single hypothesis for each sentence in the document, while "references" means "A **sequence of reference documents** with document being defined as a sequence of reference strings" (according to the [documentation](https://github.com/mjpost/sacrebleu/blob/5af5a3afd859f5825812feb14084a30b34960ee3/sacrebleu/compat.py#L22)). This is also reflected in the method parameters signature (`hypotheses: Sequence[str], references: Sequence[Sequence[str]]`). Unfortunately, both `[["sent 1", "sent 2"]]` and `["sent 1", "sent 2"]` and even a single string `"sent 1"` pass the `Sequence[Sequence[str]]` type check (I am not sure why). Maybe we could add an explicit check for this common misuse.

Oh, got it. Yes, I was using it wrong. Thanks for the help:)
