### ISSUE TITLE
documentation: add example of using sacrebleu as a library

### ISSUE THREAD

**Issue by Guitaricet** [mjpost/sacreBLEU#48]
Currently, it is not clear how to use sacrebleu for validation inside python code.
Docstrings for `raw_corpus_bleu` and `corpus_bleu` do not provide examples and what `sys_stream` and `ref_streams` actually are

I tried to use it like this:
```python
ref_t = [['this is an example translation', 'this is an example'], ['this is another example but only with one reference translation']]                                                                                

pred_t = ['this is an example translation', 'this is another example translation']                                                                                                                                     

sacrebleu.raw_corpus_bleu(pred_t, ref_t)
# or
sacrebleu.corpus_bleu(pred_t, ref_t)
```

Which is consistent with function signature

```python
sys_stream: Union[str, Iterable[str]],
Union[str, List[Iterable[str]]]
```

But this error happends:
`EOFError: Source and reference streams have different lengths!`

Some examples or more detailed parameter explanation would really help.

And thank you for your work on standardization of BLEU computation!

**UPD:**
figured out how to use `corpus_bleu` with _one_ reference translation for each sentence (but not multiple)

```python
ref_t = ['this is an example translation', 'this is another example but only with one reference translation']             

pred_t = ['this is an example translation', 'this is another example translation']                                                                                                                                     

sacrebleu.corpus_bleu(pred_t, [ref_t])
```

**Comment by mjpost** [comment]
I agree it's bad. From memory, I believe that the ref streams is a list of streams. What you here is a list of sentences, which is why your invocation

```
sacrebleu.corpus_bleu(pred_t, [ref_t])
```

works. For multiple refs, use

```
sacrebleu.corpus_bleu(pred_t, [ref1_stream, ref2_stream, ...])
```

**Comment by mjpost** [comment]
(In your first example above, your second stream has only one entry, instead of the required two).

**Comment by mjpost** [comment]
If you wanted to fix up the documentation a bit and submit a PR, we would be grateful!

**Comment by Guitaricet** [comment]
Actually, I am not sure I understand what stream is.
Is in an iterable of different examples of an iterable of different translations of one example?

**Comment by martinpopel** [comment]
Stream is an iterable of sentences in the test corpus.
If you have multiple reference translations, you will have multiple reference streams.

Note that all streams must have the same number of sentences and no sentence can be `None` (i.e. omitted/not available) in any stream.
This effectively means that all sentences must have the same number of reference translations, which is true for all the test-sets registered in SacreBLEU (actually, most of them are single-reference and just a few two-reference).
If you happen to have a different number of references for each sentence, I suggest that you "pad" the missing references with e.g. the first reference before using SacreBLEU - this will give you the expected BLEU score (because duplicating a reference does not affect BLEU).
Using an empty string for padding (substituting missing references) is not recommended because it may unfairly improve the brevity penalty (and thus the final BLEU) if any hypothesis sentence is shorter than half of the shortest reference (because SacreBLEU uses the "[closest length](https://github.com/mjpost/sacreBLEU/blob/7051063/sacrebleu.py#L1050-L1069)" heuristics; when using the "[shortest length](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/mteval-v14.pl#L38)" the unwanted effect would be even bigger).
