### ISSUE TITLE
sentence_bleu calculation fails

### ISSUE THREAD

**Issue by hlkcrcck** [mjpost/sacreBLEU#64]
Sentence level BLEU calculation from Python api gave 0.0 score on arbitrary samples in a dataset while corpus level calculations works correctly.

![image](https://user-images.githubusercontent.com/7250168/75343164-ecdedd00-58a8-11ea-8a1a-9e42d7bf514f.png)

reproducible versions: 1.2.11 - 1.4.2.

**Comment by martinpopel** [comment]
This is expected. `sentence_bleu` [just calls](https://github.com/mjpost/sacreBLEU/blob/326c43b8/sacrebleu.py#L1336-L1357) `corpus_bleu`, but it has different default values for the optional parameters `smooth_method` and `use_effective_order`. If you call the methods with the same `smooth_method`, you will get the same result.

`sacrebleu.sentence_bleu(source_bitexts[0], target_bitexts[0], 'exp')` should give you BLEU=26.08, i.e. the same BLEU as `corpus_bleu`.

BTW: `source_bitexts` is a confusing name, it should be the hypothesis (MT output, not the source language) and it is not a bitext (it is monolingual).

More details:
Your `source_bitexts` sentence has no 4-gram matching the `target_bitexts` sentence. (If you add e.g. *playing* after *is* into the target, there will be 1 matching 4-gram and no smoothing will be needed and the scores will be the same disregarding the option).
BLEU is defined as a geometric average of 1-4 gram precisions, so if one of the numbers (the 4-gram precision) is 0, the whole BLEU is 0. To prevent this, sacreBLEU uses different smoothing methods: `corpus_bleu` uses `exp` smoothing, which works out of the box and does not need any other parameter. `sentence_bleu` uses `floor` smoothing, which needs a `smooth_value` parameter, which is unfortunately set to 0 (i.e. no smoothing) by default. This unfortunate default value will be hopefully fixed by merging #55.

**Comment by hlkcrcck** [comment]
@martinpopel thank you for this kind and detailed explanation. I was using [vizseq](https://github.com/facebookresearch/vizseq) to get sentence level bleu scores which uses sacrebleu under the hood. So apperantly, they are also using the "floor" smoothing method which makes the sentence level results very sparse and confusing. Maybe I should reopen this issue on the vizseq side to fix that behaviour or make it optional.

Also sorry for the confusing namings, I just wanted to show the problem very quickly and changed the strings but I forgot to change the variable names.
