### ISSUE TITLE
Getting the hash signature when using this tool as a python library?

### ISSUE THREAD

**Issue by matejklemen** [mjpost/sacrebleu#75]
Hi,
thanks for this convenient tool. :slightly_smiling_face:

I'm using it via python calls and I can't seem to find an easy way to obtain the signature of used settings (for reproducible calculation). Am I missing something or is there no easy way to do this?

**Comment by martinpopel** [comment]
When using sacreBLEU as a Python library you have full control over all the parameters (including the sacreBLEU version, i.e. `sacrebleu.__version__`, depending on which version you installed with pip) and you usually provide your own references, so I don't see much sense in the signature, but anyway:
```python
import sacrebleu
from collections import namedtuple
Args = namedtuple('Args', 'tokenize smooth lc test_set langpair origlang subset short')
args = Args('13a', 'exp', False, None, None, None, None, False)
refs = [['The dog bit the man.', 'It was not unexpected.', 'The man bit him first.'],
        ['The dog had bit the man.', 'No one was surprised.', 'The man had bitten the dog.']]
sys = ['The dog bit the man.', "It wasn't surprising.", 'The man had just bitten him.']
bleu = sacrebleu.corpus_bleu(sys, refs, smooth_method=args.smooth, lowercase=args.lc, tokenize=args.tokenize)
print(bleu)
print(sacrebleu.bleu_signature(args, numrefs=len(refs)))
```
Of course, this is hacky a brittle - new sacreBLEU versions can add more arguments needed for the signature. Also, I ignore e.g. `args.smooth_value` because it is not currently included in the signature (although it should, if we want the signature to guarantee fully reproducible scores).

We could consider adding the signature into the BLEU object returned by `corpus_blue` (so you could `print(bleu.signature)`). However, currently the API does not support this because `corpus_bleu` does not support e.g. downloading the official WMT test sets. So I am not sure if this is a good idea.

**Comment by matejklemen** [comment]
Yeah, it would be useful for convenience, though I imagine there's not many cases where a user can't just use the CLI version instead (and get the hash automatically), so it's probably not a high priority task.  

Thanks for the answer!
