### ISSUE TITLE
[Question] How to interpret the evaluation metric for translation?

### ISSUE THREAD

**Issue by gtshs2** [mjpost/sacrebleu#80]
I can find the evaluation metric in the README file as below.
BLEU+case.mixed+lang.de-en+test.wmt17 = 32.97 66.1/40.2/26.6/18.1 (BP = 0.980 ratio = 0.980 hyp_len = 63134 ref_len = 64399)

For  32.97, I think that it is a cased BLEU4.
I wonder about the meaning of the other performance metrics.

Is 66.1/40.2/26.6/18.1 also a BLEU score? Could you explain the difference between these BLEU scores and BLEU4(32.97)?
Could you explain the meaning of BP and ratio?

**Comment by martinpopel** [comment]
> BLEU+case.mixed+lang.de-en+test.wmt17 = 32.97 66.1/40.2/26.6/18.1 (BP = 0.980 ratio = 0.980 hyp_len = 63134 ref_len = 64399)
>
> For 32.97, I think that it is a cased BLEU4.

Yes, the signature contains `case.mixed`, so it is the cased-sensitive variant.
I suggest to not introduce terms like "BLEU4" because it has been used in various papers with various meanings - usually "the standard BLEU, i.e. computed on unigrams up to 4grams", but rarely also "BLEU on 4 references".

> Is 66.1/40.2/26.6/18.1 also a BLEU score?

No. These are the unigram/bigram/trigram/4gram (modified) precision scores. 

> Could you explain the difference between these BLEU scores and BLEU4(32.97)?

BLEU is computed as the geometric mean of the (modified) precisions multiplied by the Brevity Penalty (BP). 
For details see [the original BLEU paper](https://www.aclweb.org/anthology/P02-1040.pdf).

> Could you explain the meaning of BP and ratio?

Let `r` be the length of the reference in words, and `c` length of the translation.
If the translation is shorter than the reference (i.e. if ratio=(`r`/`c`)<1), BP=exp(1-`r`/`c`). Otherwise (i.e. if ratio ≥ 1), BP=1.

> I can find the evaluation metric in the README file as below.

Yes, maybe someone could send a PR, adding a short explanation and a link to the Papineni et al. paper to the README.
