### ISSUE TITLE
Enhancement: Add support for Indian languages

### ISSUE THREAD

**Issue by bhaddow** [mjpost/sacrebleu#89]
Hi
As far as I can see, sacrebleu does not have support for Indian languages. This should be a matter of adding a an option to call the tokenizer in https://github.com/anoopkunchukuttan/indic_nlp_library . I see the tokenizer is getting a refactoring at the moment. I'm happy add indicnlp - just wondering what the preferred route would be, and plans for the tokenizer?

cheers - Barry

**Comment by bhaddow** [comment]
Actually Indic tokenisation is generally straightforward so this may be a non-issue, if the international option handles it.

**Comment by martinpopel** [comment]
I would say that tokenization in BLEU does not need to be perfect from the linguistic and language-specific point of view, it should be just approximately adequate (separating punctuation, not keeping the whole sentence as a single token in Chinese/Japanese/Thai...), standardized (easy to replicate outside of SacreBLEU) and stable (so that it does not change with each version of SacreBLEU/IndicNLP/MeCab). 

I am no expert on the languages of India, but I think that only ancient forms of the languages (vedic Sanskrit,  Kannada) use script continuo (no spaces between words), otherwise the current `-tok intl` should be OK. However, IndicNLP does not seem to handle scripto continuo anyway, I see just a [list of punctuation](https://github.com/anoopkunchukuttan/indic_nlp_library/blob/master/indicnlp/tokenize/indic_tokenize.py#L23-L24), which should be a subset of [all Unicode punctuation symbols](https://github.com/mjpost/sacrebleu/blob/32c54cd/sacrebleu/tokenizer.py#L66), so I don't see any strong reason for adding IndicNLP into SacreBLEU.

**Comment by bhaddow** [comment]
Makes sense.
